name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    uses: rarebit-one/.github/.github/workflows/reusable-maven-central-release.yml@v1
    with:
      project-name: ktor-armour
    permissions:
      contents: write
    secrets: inherit
